apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
    envFrom:    # here wwe are refering whole secret
      - secretRef:
          name: app-secret
    env: 
      - name: APP_COLOR
        valueFrom:
          secretKeyRef:
            name: app-secret  # here we are referencing single value from secret
            key: APP_COLOR
