apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
securityContext:   # security context for pod
  runAsUser: 1000
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["sleep","3000"]
    securityContext:  # security context for container
      runAsUser: 1000
      capabilities:   # capabilities are supported only at container level and not at pod level
        add: ["MAC_ADMIN"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
