apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp  # labels of pod to link against te service so that these service is linked to pod
  ports:
  - port: 80   # port of service (only port is mandatory)
    targetPort: 80 #port of pod  if we do not provide target port its assumed to be same as port
    nodePort: 30008 # node port

