apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploumeny
  labels:
    app: server
spec:
  replicas: 3
  selector:
    matchLabels:
      type: server
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
        type: server
    spec:
      containers:
        - name: nginx-container
          image: nginx