apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    name: nginx
    type: server
spec:
  containers:
  - name: nginx-container
    image: nginx
  initContainers:
  - name: db-checker
    image: busybox
    command: ['wait-for-db-to-start.sh']
    restartPolicy: Always # here restart policy makes sure that this side car always runs