apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: ubutnu
    image: ubuntu-sleeper
    command: ["sleep 2.0"]  #to override entry point in docker file
    args: ["10"]  # to override cmd in docker file which is args
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
