apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
    envFrom:    # here wwe are refering whole config map
      - configMapRef:
          name: app-config
    env: 
      - name: APP_COLOR
        valueFrom:
          configMapKeyRef:
            name: app-config  # here we are referencing single value from config map
            key: APP_COLOR
